### ISSUE TITLE
Single HTML file of a book

### ISSUE THREAD

**Issue by geoffreymcgill** [retypeapp/retype#85]
### Discussed in https://github.com/retypeapp/retype/discussions/84

<div type='discussions-op-text'>

<sup>Originally posted by **larmarange** July 21, 2021</sup>
Do you have any plan for allowing to generate (in addition of the website) an HTML file (ideally self-contained) containing all the book allowing to propose to readers to download the overall book and/or to print it as a PDF with their browser.</div>

**Comment by geoffreymcgill** [comment]
Yes, 100% this is happening. I've had on my TODO list since the beginning of Retype.

We will be providing several print friendly, file download, and eBook download options. This will include: 

1. Print friendly stylesheet, so printing any individual page directly from the browser looks awesome
2. A per page .pdf download option
3. An entire content (the "Book") in at least several different formats:
    1. .epub (all content)
    2. .ibooks (might not be required)
    3. .pdf (per page & all book)
    4. .html (might not be required)

We haven't started on any of these features yet, but they are technically trivial for us to implement. Most of the development time will be taken up with UI design and testing.

I'm not exactly sure what release the above (or some of the above) features will be implemented, but it is a priority. I don't think we can implement within the `v1.9.0` cycle, but _maybe_ `v1.10.0`. 

We're a small team and working our way through all the feature requests as fast as we can. That said, all of the above will supported by Retype. With some luck, in Q4 2021.

Hope this helps answer your questions.

**Comment by larmarange** [comment]
Yes thanks. That would be great

**Comment by Zerotask** [comment]
It would be great to build a pdf with an optional CLI flag.

**Comment by arminus** [comment]
Looking forward to this, too. Does anyone see a "hacked" (pandoc?) way of getting something out, even if not perfect?

**Comment by DannyBen** [comment]
> Does anyone see a "hacked" (pandoc?) way of getting something out, even if not perfect?

There should be a relative easy way to hack something up.

1. A script that iterates over the files, and removes or modifies all non-standard markdown elements
2. Then, it concatenates the output to a single markdown file
3. Then, you can just preview it with any markdown previewer - personally, I am using my own CLI to preview READMEs ([madman](https://github.com/DannyBen/madman) and save the HTML, or use any other "markdown to HTML" conversion technique.

The bigger challenge, would be to convert the non standard markdown elements.

Another similar approach, would be to

1. Write a script that iterates and concats all your markdown files, and saves the output back to the source folder
2. Open the result in Retype... :)

**Comment by p0fi** [comment]
Any updates on PDF support? This is really the missing thing here!

**Comment by DannyBen** [comment]
Converting individual markdown files into one cohesive PDF book is not a trivial task.

From dev perspective, it involves two tasks:

### Task 1: Concatenating markdowns, which will require:

- Having a new template that understands "pages", has a Table of Contents and other elements in preparation for PDF export.
- Being able to adjust all links to be internal
- Being able to adjust all header links, to distinguish from one another.
- More

### Task 2: Converting markdown to HTML and then to PDF

While it can be done in a server environment (one that render server-side markdown to HTML), it is - to my knowledge - quite impossible to do on a client side, without bringing in bloated software to do so.

Personally, I do not know of any other documentation tool generator that does that - I would love to be enlightened if there is any.

I believe the only course of action for Retype developers (if any) is to render a special HTML page (say "my-retype-site.com/book"), which will create the HTML render of everything (i.e. Task 1), and then the user can use their already available "Download as PDF" in Chrome or other modern browser.

**Comment by p0fi** [comment]
Im well aware that this is not trivial, it's a really important feature nevertheless in my eyes.

> Personally, I do not know of any other documentation tool generator that does that - I would love to be enlightened if there is any.

Gitbook does that. See [Gitbook Docs – PDF Export](https://docs.gitbook.com/tour/pdf-export)

**Comment by DannyBen** [comment]
I understand. But Gitbook is a hosted service, retype is a static site generator.

**Comment by lnarynskyyi** [comment]
> * Print friendly stylesheet, so printing any individual page directly from the browser looks awesome
> * A per page .pdf download option
> * An entire content (the "Book") in at least several different formats:
>   
>   1. .epub (all content)
>   2. .ibooks (might not be required)
>   3. .pdf (per page & all book)
>   4. .html (might not be required)

I understand the additional complexity involved in # 3 (entire "book"), but the first two points seem much more trivial. Since Retype doesn't currently support at-rules `@page { @top-right {...}}` it's damn near impossible to get a nice printout of a single article. 

Any updates on this @geoffreymcgill?

**Comment by p0fi** [comment]
Don't hope on anything here I would say. I guess you can consider this project dead.

**Comment by geoffreymcgill** [comment]
@p0fi Nice. Thanks for that.

**Comment by ApolonTorq** [comment]
Just an FYI. Refer to #628 for a somewhat "hacky" workaround that can be used as an interim measure for single page pdfs.

**Comment by geoffreymcgill** [comment]
> 1. Print friendly stylesheet, so printing any individual page directly from the browser looks awesome

A bunch of work has gone into make a print friendly stylesheet for the page and pages are definitely printing much better now.

The new print friendly stylesheet will be included in the upcoming v3.9.0 release.

If you notice any issues with the print formatting, please let us know.

> 2. A per page .pdf download option
> 3. An entire content (the "Book") in at least several different formats

Generation and download of a .pdf has not been implemented, yet. This functionality is still a high priority for us, but it will have to wait for a future release.

**Comment by DannyBen** [comment]
> Yes, 100% this is happening

I am not complaining, but I would like to bump this 5 year old issue with a hopefully easy to implement feature.

- [x] Ensure there is a solid print friendly CSS
- [ ] Provide a configuration option that allows enabling *The Big Beautiful Book Page*™ - something like
      `book: { enabled: true, path: /book }`
- [ ] When enabled, this path follows the same logic that is implemented in the sidebar and iterates over all the files (respecting sort order), and concatenates them to a single HTML, using a "no sidebar" layout.
- [ ] Ensure the print CSS has a break before each H1, or new document.

That's it. This in itself, will allow users to view the full page, press Ctrl+P, and print it to PDF.

I really feel the absence of this feature, as one of my basic use cases is to provide a "packaged" nicely formatted document to interested parties.
